//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitis.Prototype.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitis.Prototype.Logic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 413b1bd0a00e46f6bf893aae80416bde.
        /// </summary>
        internal static string DefaultDeploymentID {
            get {
                return ResourceManager.GetString("DefaultDeploymentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q4W4vqQATcVq+EqCDbuG5TwExkMTD5YmRQ4IRW8R0Wk0H2GOF2leRHFy2I2EqF/C22Oya4TeqwYawfOVTgbz2A==.
        /// </summary>
        internal static string DefaultStorageAccountKey {
            get {
                return ResourceManager.GetString("DefaultStorageAccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to azdem.
        /// </summary>
        internal static string DefaultStorageAccountName {
            get {
                return ResourceManager.GetString("DefaultStorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Memory\Available Bytes.
        /// </summary>
        internal static string MemoryAvailableBytes {
            get {
                return ResourceManager.GetString("MemoryAvailableBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string MonitisCPUParameter {
            get {
                return ResourceManager.GetString("MonitisCPUParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeMemory.
        /// </summary>
        internal static string MonitisFreeMemoryParameter {
            get {
                return ResourceManager.GetString("MonitisFreeMemoryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Processor(_Total)\% Processor Time.
        /// </summary>
        internal static string ProcessorTimeCounter {
            get {
                return ResourceManager.GetString("ProcessorTimeCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostWorkerRole_IN_0.
        /// </summary>
        internal static string RoleInstanceName {
            get {
                return ResourceManager.GetString("RoleInstanceName", resourceCulture);
            }
        }
    }
}
